first p

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,15 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Check if PYFILE is set and is a file
+[ -z "$PYFILE" ] && {
+  echo "Error: PYFILE environment variable not set."
+  exit 1
+}
+
+[ ! -f "$PYFILE" ] && {
+  echo "Error: Python file '$PYFILE' not found."
+  exit 1
+}
+
+# Run the Python script
+python3 "$PYFILE"
